### ISSUE TITLE
Access issues

### ISSUE THREAD

**Issue by BingzheZhou** [courses-at-nju-by-hfwei/compilers-lectures#4]
I tried to access the lectures for this module but the page was not found.

**Comment by hengxin** [comment]
@BINGZHEZHOU Some links in README are broken. Fixed. Please check them again.

**Comment by BingzheZhou** [comment]
Dear Dr.Wei
Thanks for your quick response. I have double-checked the repo again, it
seems that the linked page is still not available. When I clicked the link
provided in the README file, the page was not found again. Two images
attached to the e-mail present the issues that I have met.

Kind regards
BINGZHE

hengxin(Hengfeng Wei) ***@***.***> 于2021年6月10日周四 下午4:05写道：

**Comment by hengxin** [comment]
@BINGZHEZHOU It works for me. (Refresh your pages?) I do not receive your email. Another way is to clone or download this repo.

**Comment by BingzheZhou** [comment]
Thanks, I will try again.
